### ISSUE TITLE
Youtube fullscreen

### ISSUE THREAD

**Issue by ditsbroefs** [StudioJunkyard/summernote-video-attributes#1]
I would like to use youtube videos and allow fullscreen. How do I best go about?

**Comment by ghost** [comment]
You would probably have set the attribute that allows Full Screen when embedding videos'.

**Comment by ditsbroefs** [comment]
Thanks. I changed line 200 (where YT iframe gets created) to
`$video=$('<iframe webkitallowfullscreen mozallowfullscreen allowFullScreen>')`
It behaves strange on Chrome, but apparently that is a know Chrome issue. All other browsers fine.

Thanks for wonderful plugin!

**Comment by tylerecouture** [comment]
Any chance of adding an `allowfullscreen` attribute option? I'm pretty sure that works with all modern broswers... use it all the time.
https://stackoverflow.com/questions/18113909/how-widely-supported-is-the-iframe-attribute-allowfullscreen
