### ISSUE TITLE
Start and End times for embedded YouTube videos

### ISSUE THREAD

**Issue by tylerecouture** [StudioJunkyard/summernote-video-attributes#13]
This would be nice to have these as field where you can enter the number of seconds.
Not sure if the other services can do it as well. Youtube allows one or the other but not both for embedded videos.

https://webapps.stackexchange.com/a/61398

**Comment by DennisSuitters** [comment]
I've embedded most of the options in the plugin directly into the VideoDialog.js for Summernote in the Skunkworks repo, I'm wondering as there are so many different options for different video services if it would be possible to do something like add the video then the script as it does to activate the insert button, can check to determine which service has been added, and just show the options for that service, much like if it's youtube then show x options via only showing the options related.
