### ISSUE TITLE
Missing part?

### ISSUE THREAD

**Issue by saosangmo** [StudioJunkyard/summernote-video-attributes#14]
I install your plugin but there is a textarea box on top of summernote and the console of Chrome displays error:

`jQuery.Deferred exception: Cannot read property 'videoUrls' of undefined TypeError: Cannot read property 'videoUrls' of undefined`

**Comment by joshbali** [comment]
Same here. Unfortunately the plugin is not usable any more with this error. For me it breaks any jQuery function after the editor. Summernote 0.8.18, jQuery v3.5.1, Chrome  91.0.4472.77. As I don't want to use another browser I haven't tested this in any of then except Chrome.

**Comment by DennisSuitters** [comment]
Sorry, I haven't looked at this sooner. I'm working on a couple of things at the moment, and I'll try and fix the outstanding issues as soon as I can.

**Comment by CrazyThursday-Vme50** [comment]
I have same problem, and when I try to click the button created by this plugin, it has another error:
```Uncaught TypeError: Cannot read properties of undefined (reading 'find')
    at Object.<anonymous> (summernote-video-attributes.js:304)
    at Function.Deferred (jquery-3.4.1.min.js:2)
    at videoAttributes.showLinkDialog (summernote-video-attributes.js:303)
    at videoAttributes.show (summernote-video-attributes.js:207)
    at pt.invoke (summernote.min 8.15.js:2)
    at HTMLButtonElement.click (summernote-video-attributes.js:67)
    at HTMLButtonElement.dispatch (jquery-3.4.1.min.js:2)
    at HTMLButtonElement.v.handle (jquery-3.4.1.min.js:2)
```

**Comment by DennisSuitters** [comment]
hm ok, that is weird. I haven't looked into this more, as I've been working on implementing most of what this plugin does into the Skunkworks version of Summernote, which would make this plugin obsolete. Unfortunately, I haven't had much time to do code atm. I'm in the middle of something on my farm right now, if I get time this evening (or if I remember), I'll have a quick look, and see if I can at least get the plugin working.

**Comment by reaua001** [comment]
Please see this branch to address this error
There is additional work on this plugin as you can't select an existing video to change its setting.

But that is not part of this issue...
See...
https://github.com/DiemenDesign/summernote-video-attributes/pull/16/commits/6c40e940a7d2e3f0d3018c06aa583ef174765620

**Comment by DennisSuitters** [comment]
Feel free to create a PR, I appreciate you looking at the issues the plugin has, I have simply not had the time to address issues lately.

**Comment by stuckonearth** [comment]
I had to move the `<script src="js/summernote-video-attributes.js"></script>` to above `</body>` tag to get rid of this error.
