### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addClass' of undefined

### ISSUE THREAD

**Issue by archthis** [StudioJunkyard/summernote-video-attributes#5]
When i go to insert video i get the Cannot read property 'addClass' of undefined. I have the latest summernote and jquery versions. I am developing on Visual Studio .net Core. It doesn't work in Chrome or Microsoftedge. Below is the code from ChromeDebugger

    if($videoSize.val()==0)$video.addClass('embed-responsive');else $video.css({'float':$videoAlignment.val()});

**Comment by s00004407** [comment]
This happens when using <Iframe> tags just upload the url thats in the browser.
