### ISSUE TITLE
TODO List: Features to add to cover issues from the main summernote repo

### ISSUE THREAD

**Issue by DennisSuitters** [StudioJunkyard/summernote-video-attributes#6]
- Youtube mobile videos are not accepted
  - https://github.com/summernote/summernote/issues/1826
- Fullscreen Youtube and correct Instagram URL
  - https://github.com/summernote/summernote/issues/2013

**Comment by WhiteDog123** [comment]
Hi. I have used your plugin, and I found one bug but I don't know where to inform you about this, so I will write here.
when I posted my video as 'Reseponsive' attribute, it works. 
but when I press 'enter', Empty space that as large as posted video will be typed.
If I check it as HTML mode, I could find the code looks like below.

 "content": "<p> <\/p><div class=\"embed-responsive embed-responsive-16by9\" style=\"float: none;\"><iframe width=\"640\" height=\"360\" class=\"embed-responsive note-video-clip\" src=\"//www.youtube.com/embed/fxl6uckaFic?&amp;loop=0\" frameborder=\"0\"><\/iframe><\/div><div class=\"embed-responsive embed-responsive-16by9\" style=\"float: none;\"><br><\/div><div class=\"embed-responsive embed-responsive-16by9\" style=\"float: none;\"><br><\/div><p><br><\/p>"

in here, you can see theres some empty video frame, that is same count of that I pressed enter.
this took me some times to why is it happening, and I figured how to solve this.

`if ($videoSize.val() == 0) {
    
                $videoHTML.addClass('embed-responsive embed-responsive-16by9');
    

      
//I just ignored this line right below.
                //$videoHTML.css({'float': $videoAlignment.val()});
    
                var videoWidth  = '640',
    
                    videoHeight = '360';
    
              }`
I just simply add the // at the apploximately line 353.
I don't have any basis on js so I cannot tell you guys why.
Anyway, here is an issue.

I used Microsoft Edge for this webpage.

**Comment by DennisSuitters** [comment]
If you have a look towards the top of the page, in the Issues tab, you'll see an button "New Issue".

I had a look at what you explained above, the behaviour happens in Chrome on Linux as well, but it's not the plugin it's the editor. As I'm part of the dev team for Summernote I'll bring this up as a bug with the other devs so we can look into it. Thanks for bringing the issue to attention.

**Comment by DennisSuitters** [comment]
I've raised this issue with the other developers.
I think the behaviour should go like this.
When editing, or inserting new content after another area, for e.g. a paragraph of content. The editor should duplicate the preceding paragraph including styles and classes as it does for every preceding element as it does now, but only for paragraph (`<p>`) elements, but not for others. If there's a space or newline, then the text should just be entered without any surrounding element seeing as the editor has toolbar options to style selected text from the styles dropdown.

**Comment by WhiteDog123** [comment]
Yes. 
The result what I got from the last, It totally looked like "Duplicating" the last paragraph, or the <div> tag and elements that it includes.
If you need any additional information(or exact behavior for cause this bug) from me, please let me notice.
I will look forward for the dev team fix this bug.
Thx for paying attention.

**Comment by DennisSuitters** [comment]
After talking to the other devs, it's a behaviour of the Browser and using Contenteditable. We're actually looking into how we can make our dom system so these issues don't occur.
After I do some gardening this afternoon I'm going to do some research into how the contenteditable dom behaviours can be modified, as I've discovered other editors have the same issue, and I figure if we can do something that overrides this behaviour it will help set Summernote apart from the other editors.
